# Generated by Django 2.2.2 on 2019-07-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_slider_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='Addimage',
        ),
    ]
