# Generated by Django 2.2.2 on 2019-07-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_auto_20190719_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='addimage',
            name='publish',
            field=models.BooleanField(null=True),
        ),
    ]
