# Generated by Django 2.2.2 on 2019-07-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_addimage_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addimage',
            name='publish',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
