# Generated by Django 2.2.2 on 2019-07-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0007_auto_20190719_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='addimage',
            name='loop_c',
            field=models.BooleanField(default=True),
        ),
    ]
